### ISSUE TITLE
driver sample fails to build in 1.6.10

### ISSUE THREAD

**Issue by ChristophHaag** [ValveSoftware/openvr#1171]
gcc 9.1.0 on Linux:
```
/home/chris/oldhome/build/openvr-github/samples/driver_sample/driver_sample.cpp: In function ‘void WatchdogThreadFunction()’:
/home/chris/oldhome/build/openvr-github/samples/driver_sample/driver_sample.cpp:106:40: error: no matching function for call to ‘vr::IVRWatchdogHost::WatchdogWakeUp()’
  106 |   vr::VRWatchdogHost()->WatchdogWakeUp();
      |                                        ^
In file included from /home/chris/oldhome/build/openvr-github/samples/driver_sample/driver_sample.cpp:3:
/home/chris/oldhome/build/openvr-github/samples/../headers/openvr_driver.h:3429:15: note: candidate: ‘virtual void vr::IVRWatchdogHost::WatchdogWakeUp(vr::ETrackedDeviceClass)’
 3429 |  virtual void WatchdogWakeUp( vr::ETrackedDeviceClass eDeviceClass ) = 0;
      |               ^~~~~~~~~~~~~~
/home/chris/oldhome/build/openvr-github/samples/../headers/openvr_driver.h:3429:15: note:   candidate expects 1 argument, 0 provided
make[2]: *** [driver_sample/CMakeFiles/driver_sample.dir/build.make:89: driver_sample/CMakeFiles/driver_sample.dir/driver_sample.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:107: driver_sample/CMakeFiles/driver_sample.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

**Comment by lubosz** [comment]
This is fixed by https://github.com/ValveSoftware/openvr/pull/1177
