### ISSUE TITLE
Can no longer create a build in Unity 5.3.4f1 due to compile error in SteamVR_LoadLevel

### ISSUE THREAD

**Issue by thestonefox** [ValveSoftware/openvr#101]
This is for SteamVR Unity Plugin build 1.0.9 (was ok in 1.0.8)

The error I get is:

Assets/SteamVR/Scripts/SteamVR_LoadLevel.cs(357,33): error CS0103: The name `Process' does not exist in the current context

On these lines:

https://github.com/ValveSoftware/openvr/blob/master/unity_package/Assets/SteamVR/Scripts/SteamVR_LoadLevel.cs#L354-L358

**Comment by LordDG** [comment]
System.Diagnostics.Process.GetCurrentProcess()

**Comment by thestonefox** [comment]
I think there is a pull request open to fix this:

https://github.com/ValveSoftware/openvr/pull/107

**Comment by aleiby** [comment]
This was fixed in 1.1.0.  Thanks.
