### ISSUE TITLE
hellovr_vulkan fails to build on linux64 (possibly GCC 4.9 specific?)

### ISSUE THREAD

**Issue by roothorick** [ValveSoftware/openvr#755]
Error output is thus:

```
/home/roothorick/dev/openvr/samples/hellovr_vulkan/hellovr_vulkan_main.cpp: In member function ‘bool CMainApplication::BInitVulkanInstance()’:
/home/roothorick/dev/openvr/samples/hellovr_vulkan/hellovr_vulkan_main.cpp:899:95: error: cannot pass objects of non-trivially-copyable type ‘__gnu_cxx::__alloc_traits<std::allocator<std::basic_string<char> > >::value_type {aka class std::basic_string<char>}’ through ‘...’
     dprintf( "Vulkan missing requested extension '%s'.\n", requiredInstanceExtensions[ nExt ] );
                                                                                               ^
hellovr_vulkan/CMakeFiles/hellovr_vulkan.dir/build.make:158: recipe for target 'hellovr_vulkan/CMakeFiles/hellovr_vulkan.dir/hellovr_vulkan_main.cpp.o' failed
make[2]: *** [hellovr_vulkan/CMakeFiles/hellovr_vulkan.dir/hellovr_vulkan_main.cpp.o] Error 1
[ 90%] Built target driver_sample
make[2]: Target 'hellovr_vulkan/CMakeFiles/hellovr_vulkan.dir/build' not remade because of errors.
CMakeFiles/Makefile2:262: recipe for target 'hellovr_vulkan/CMakeFiles/hellovr_vulkan.dir/all' failed
make[1]: *** [hellovr_vulkan/CMakeFiles/hellovr_vulkan.dir/all] Error 2
```

Changing the offending line thus gets it to build:
```
				dprintf( "Vulkan missing requested extension '%s'.\n", requiredInstanceExtensions[ nExt ].c_str() );
```
